services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    depends_on:
      - mysql
    entrypoint: [ "flyway", "migrate" ]
    environment:
      FLYWAY_URL: jdbc:mysql://mysql:${DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
      FLYWAY_USER: ${DB_USER}
      FLYWAY_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./migrations:/flyway/sql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - mysql
      - flyway
    ports:
      - "8080:8080"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}

volumes:
  mysql-data: